server:
   port: 8090
   servlet:
      context-path: /woodstories
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/woodstories_schema
      username: root
      password: root
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
         ddl-auto: update

mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testsurnametestname0@gmail.com
    password: qwerty123456&&&
    port: 587
    protocol: smtp
    auth: true
    starttls-enable: true
    test-connection: false